{{- if and .Values.prometheusRule.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "helm-exporter.fullname" . }}-rule
  namespace: {{ default .Release.Namespace .Values.prometheusRule.namespace }}
  labels:
    {{- include "helm-exporter.labels" . | nindent 4 }}
    {{- with .Values.prometheusRule.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: HelmExporter
      rules:
        {{- if .Values.prometheusRule.createDefaultRules }}
        - alert: HelmChartOutOfDate
          expr: helm_chart_outdated > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            description: This alert is fired when a helm chart for an installed app is outdated
            summary: "App {{ "{{ $labels.release }}" }} installed with chart {{ "{{ $labels.chart }}" }} in namespace {{ "{{ $labels.namespace }}" }} currently is version {{ "{{ $labels.version }}" }}. A new version {{ "{{ $labels.latestVersion }}" }} has recently been released, consider upgrading"
        {{- end }}
{{- end }}
